from __future__ import annotations

FEATURE_ROWS = [
    ('shared_charge_status', 'shared', 'all', '充电状态编码', 'category'),
    ('shared_soc', 'shared', 'all', '窗口末尾SOC', '%'),
    ('shared_speed', 'shared', 'all', '窗口末尾车速', 'km/h'),
    ('shared_sum_voltage', 'shared', 'all', '窗口末尾总电压', 'V'),
    ('shared_sum_current', 'shared', 'all', '窗口末尾总电流', 'A'),
    ('shared_insulation_resistance', 'shared', 'all', '窗口末尾绝缘电阻', 'ohm'),
    ('shared_v_range', 'shared', 'all', '窗口内单体电压极差最大值', 'V'),
    ('shared_t_range', 'shared', 'all', '窗口内温度极差最大值', 'degC'),
    ('sd_cell_dev_min', 'self_discharge', 'sd', '最弱单体相对中位数偏移最小值', 'V'),
    ('sd_cell_dev_slope', 'self_discharge', 'sd', '最弱单体偏移趋势', 'V'),
    ('sd_weak_cell_repeat_ratio', 'self_discharge', 'sd', '最低电压单体重复占比', 'ratio'),
    ('sd_rest_drop_rate', 'self_discharge', 'sd', '窗口内最弱单体压降', 'V'),
    ('isc_module_vdrop_max', 'internal_short', 'isc', '模组最小电压最大瞬时跌幅', 'V'),
    ('isc_module_vrange', 'internal_short', 'isc', '模组电压极差', 'V'),
    ('isc_module_tmax', 'internal_short', 'isc', '模组最高温度', 'degC'),
    ('isc_module_trise_max', 'internal_short', 'isc', '模组最大温升速率', 'degC'),
    ('conn_dvdt_max', 'connection', 'conn', '单体电压变化率最大值', 'V/frame'),
    ('conn_icc_min', 'connection', 'conn', '相邻单体ICC最小值', 'score'),
    ('conn_neighbor_response_gap', 'connection', 'conn', '邻域响应差异', 'V'),
    ('conn_abnormal_point_ratio', 'connection', 'conn', '异常点占比', 'ratio'),
    ('samp_local_median_residual', 'sampling', 'samp', '相对邻域中位数偏差', 'V'),
    ('samp_sensor_jump_count', 'sampling', 'samp', '异常跳变次数', 'count'),
    ('samp_pack_sum_residual', 'sampling', 'samp', '单体电压和总压残差', 'V'),
    ('samp_abnormal_count_ratio', 'sampling', 'samp', '采样异常点累计比例', 'ratio'),
    ('ins_rins_min', 'insulation', 'ins', '绝缘电阻最小值', 'ohm'),
    ('ins_rins_slope', 'insulation', 'ins', '绝缘电阻变化趋势', 'ohm'),
    ('ins_threshold_margin', 'insulation', 'ins', '相对安全阈值裕度', 'ohm'),
    ('ins_low_rins_persistence', 'insulation', 'ins', '低绝缘持续帧数', 'count'),
]
